eulesv/dashboard
svconectado/webhook_sms_request pull request #3
Opened 2020-04-02 06:48 UTC by eulesv

- El dashboard está puede ser accedido en la ruta /sidekiq
- La credencial es configurada en variables de entorno
- Debido a que se usa autenticación básica, la implementación en producción requiere SSL

2020-04-02 13:34 UTC, lekastillo approved these changes

2020-04-02 13:35 UTC, lekastillo approved these changes

2020-04-02 17:37 UTC, trejo08 requested changes

2020-04-02 17:37 UTC, trejo08 commented on config.ru
> +use Rack::Env
this line is unnecessesary beceause it's already loaded by the block between lines `9 - 15`, please check it

2020-04-03 03:19 UTC, trejo08 commented on config.ru
> +  base_path = File.expand_path(File.dirname(File.dirname(__FILE__)))
good catch, more redeable

2020-04-03 07:11 UTC, eulesv commented on config.ru
> +  base_path = File.expand_path(File.dirname(File.dirname(__FILE__)))
La línea ya fue eliminada, con esto queda todo como se esperaba, creo que pueden proceder con el merge

2020-04-03 07:15 UTC, trejo08 approved these changes

2020-04-03 07:15 UTC, merged